# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='usertype',
            field=models.IntegerField(choices=[(0, 'Regular'), (1, 'Owner')], default='0', help_text="If you own a food truck please select 'Owner'"),
        ),
    ]
