# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=100)),
                ('truck_picture', models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path)),
                ('short_description', models.CharField(max_length=512)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=64)),
                ('is_truck_owner', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.User'),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Truck'),
        ),
        migrations.AddField(
            model_name='hours',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Truck'),
        ),
    ]
