# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-31 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=256)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_description', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_name', models.CharField(max_length=100)),
                ('truck_picture', models.ImageField(blank=True, null=True, upload_to=website.models.get_image_path)),
                ('short_description', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('truck_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menu_item',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Truck'),
        ),
        migrations.AddField(
            model_name='hours',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Truck'),
        ),
    ]
