# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 23:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170416_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='truckhours', to='website.Truck'),
        ),
    ]
