# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-16 23:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170416_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(blank=True, max_length=256, null=True)),
                ('longitude', models.CharField(blank=True, max_length=256, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucklocation', to='website.Truck')),
            ],
        ),
    ]
