# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-04-17 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_location_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='day',
            field=models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')]),
        ),
    ]
