# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170417_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='day',
            field=models.IntegerField(choices=[(1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'Saturday')]),
        ),
    ]
