# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20170420_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours',
            name='thrusday',
        ),
        migrations.AddField(
            model_name='hours',
            name='thursday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='friday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='monday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='saturday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='sunday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='tuesday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='hours',
            name='wednesday',
            field=models.CharField(blank=True, help_text='256 character limit to express hours as you would like. We recommend something similar to 11am-5pm', max_length=256, null=True),
        ),
    ]
